### DISCUSSION TITLE
Branch coverage always shows up as "no data found" in the PR comment

### DISCUSSION THREAD

**Discussion by balaji-srin** [zgosalvez/github-actions-report-lcov#17] [Q&A] [answered]
Hello all,

I am using the v1.4.0 version of github-actions-report-lcov. This is how I invoke it from my github workflow.

```
      - name: Report code coverage
        uses: zgosalvez/github-actions-report-lcov@v1.4.0
        with:
          coverage-files: coverage.info
          github-token: ${{ secrets.GITHUB_TOKEN }}
          minimum-coverage: 10
          artifact-name: code-coverage-report
          working-directory: local
```

I notice that when the job completes, the PR comment it leaves always has "no data found" for the branch coverage. It does however report reasonable numbers for lines and functions coverage. What could be wrong? In the log, I see the following (just pasting the relevant lines)

```
....
Writing directory view page.
Overall coverage rate:
  lines......: 47.2% (7623 of 16157 lines)
  functions..: 53.6% (1016 of 1896 functions)
  branches...: 37.0% (3142 of 8500 branches)
Total file count: 841 ---- Processed file #208 (24.7%)
Total file count: 841 ---- Processed file #415 (49.3%)
Total file count: 841 ---- Processed file #627 (74.5%)
Total file count: 841 ---- Processed file #834 (99.1%)
Total size of all the files uploaded is 2156030 bytes
Finished uploading artifact code-coverage-report. Reported size is 2156030 bytes. There were 0 items that failed to upload
[command]/usr/bin/lcov --add-tracefile coverage.info --output-file /tmp/__zgosalvez_github-actions-report-lcov/lcov.info
Combining tracefiles.
Reading tracefile coverage.info
Writing data to /tmp/__zgosalvez_github-actions-report-lcov/lcov.info
Summary coverage rate:
  lines......: 47.2% (7623 of 16157 lines)
  functions..: 53.6% (1016 of 1896 functions)
  branches...: no data found
[command]/usr/bin/lcov --summary /tmp/__zgosalvez_github-actions-report-lcov/lcov.info
Reading tracefile /tmp/__zgosalvez_github-actions-report-lcov/lcov.info
Summary coverage rate:
  lines......: 47.2% (7623 of 16157 lines)
  functions..: 53.6% (1016 of 1896 functions)
  branches...: no data found
[command]/usr/bin/lcov --list /tmp/__zgosalvez_github-actions-report-lcov/lcov.info --list-full-path
Reading tracefile /tmp/__zgosalvez_github-actions-report-lcov/lcov.info
                                                                                                                                                   
```

As can be seen, the branch coverage does get populated correctly in what appears to be the first of the three runs. The second and third runs however do not have any branch coverage data. Anyone knows why lcov is invoked three times? And why the branch coverage data gets removed after the second and third runs?
