### ISSUE TITLE
Process /usr/bin/genhtml failed with exit code 255

### ISSUE THREAD

**Issue by RatakondalaArun** [zgosalvez/github-actions-report-lcov#10]
I am trying to generate a coverage report for a package but it fails saying

![image](https://user-images.githubusercontent.com/47482264/129905958-da429e3f-9272-4cf6-ab2f-728d2f99a500.png)

<details>
<summary>ci-workflow.yaml</summary>

 ```yaml
env:
  PACKAGE_PATH: packages/bridge_common

defaults:
  run:
    shell: bash
    working-directory: packages/bridge_common

 coverage:
    name: 💹 Generate coverage report
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: 🔧 Setup Dart SDK
        uses: dart-lang/setup-dart@v1.2

      - name: 🏗 Install dependencies
        run: dart pub get

      - name: 📝 Generate Coverage
        working-directory: packages/
        run: ./coverage.sh bridge_common

      - name: 📃 Report Coverage
        uses: zgosalvez/github-actions-report-lcov@v1.3.2
        with:
          coverage-files: coverage/lcov.info
          minimum-coverage: 0 # todo: update minimum coverage
          artifact-name: common-coverage-report
          github-token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: ${{env.PACKAGE_PATH}}
```
</details>

**Comment by zgosalvez** [comment]
The log file shows something similar to a previous issue that I resolved in this https://github.com/zgosalvez/github-actions-report-lcov/issues/9#issuecomment-894768327. Basically, your log doesn't show any input, however it appears your `coverage-files` input is properly set. I'm wondering if this https://github.com/zgosalvez/github-actions-report-lcov/blob/49af65b0586c274a625a41a2dc8aaaae7d00568b/src/main.js#L16 is the cause of the problem, OR maybe your `coverage/lcov.info` doesn't exist. Thoughts?

**Comment by RatakondalaArun** [comment]
Hey @zgosalvez 
I put some log statements and verified that `coverage/lcov.info` exists

```log
Generating LCOV report...
Generated coverage in /home/runner/work/****/*******/packages/bridge_common

.
..
coverage.json
lcov.info
```
After trying different setting it seems to work now below is my changed workflow
```yaml
  coverage:
    name: 💹 Generate coverage report
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: 🔧 Setup Dart SDK
        uses: dart-lang/setup-dart@v1.2

      - name: 🏗 Install dependencies
        run: dart pub get

      - name: 📝 Generate Coverage
        working-directory: packages/
        run: ./coverage.sh bridge_common && ls -a bridge_common && ls -a bridge_common/coverage

      - name: 📃 Report Coverage
        uses: zgosalvez/github-actions-report-lcov@v1.3.2
        with:
          coverage-files: "packages/bridge_common/coverage/*.info"
          minimum-coverage: 0 # todo: update minimum coverage
          artifact-name: common-coverage-report
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # working-directory: packages/bridge_common/
```
