### ISSUE TITLE
genhtml step fails

### ISSUE THREAD

**Issue by mpconte** [zgosalvez/github-actions-report-lcov#15]
Using this sample workflow step:

        - name: Report LCOV report        
          uses: zgosalvez/github-actions-report-lcov@v1.4.0
          with:
            coverage-files: coverage/*.info
            artifact-name: code-coverage-report     

I get the following error:

`/usr/bin/genhtml --rc lcov_branch_coverage=1 --output-directory /tmp/__zgosalvez_github-actions-report-lcov/html`
`genhtml: No filename specified`

**Comment by zgosalvez** [comment]
This usually happens when the coverage files cannot be found. Please see #9 and let me know if that helps!

**Comment by mpconte** [comment]
Thanks for responding. I still get the same error though.

Here's more from my workflow:

```
...
      - name: Run unit tests
        run: flutter test test --coverage --coverage-path=coverage/lcov.unit_test.info  
          
      - name: Run integration tests
        run: flutter test integration_test --device-id windows --coverage --coverage-path=coverage/lcov.integration_test.info

      - name: Upload test coverage report
        uses: actions/upload-artifact@v2.3.1
        with:
          name: flutter_demo_test_coverage
          path: coverage

report_test_results:
      runs-on: ubuntu-latest
      needs: build_and_test
      steps:
        - uses: actions/download-artifact@v2
          with:
            name: flutter_demo_test_coverage            

        - name: Report unit test coverage report        
          uses: zgosalvez/github-actions-report-lcov@v1.2.0
          with:
            artifact-name: unit-test-code-coverage-report  
            coverage-files: coverage/lcov.unit_test.info      

        - name: Report integration test coverage report        
          uses: zgosalvez/github-actions-report-lcov@v1.2.0
          with:
            artifact-name: unit-integration-code-coverage-report  
            coverage-files: coverage/lcov.integration_test.info       
```
