### ISSUE TITLE
genhtml: No filename specified

### ISSUE THREAD

**Issue by simonppg** [zgosalvez/github-actions-report-lcov#16]
I can find the correct way to set lcov output file to the this github action,

I have this configuration:

```yaml
   - name: Coverage
      working-directory: ${{github.workspace}}/build
      run: make coverage && ls -l && pwd

    - name: Report code coverage
      uses: zgosalvez/github-actions-report-lcov@v1
      with:
        coverage-files: lcov.coverage.info
        minimum-coverage: 90
        artifact-name: code-coverage-report
        github-token: ${{ secrets.GITHUB_TOKEN }}
        working-directory: ${{github.workspace}}/build
```
The Coverage stage generate the file lcov.coverage.info on the build directory which is the working directory on the github action, but It can't pick it up.

Could anybody point me to the right direction to fix this?

here is a screenshot of the error and a link to the [failing runner](https://github.com/simonppg/Break_it_all/runs/5808035468?check_suite_focus=true)
 
![Report lcov](https://user-images.githubusercontent.com/3270997/161448204-19ce504d-804e-490d-8e60-141188e1aac5.png)
