### ISSUE TITLE
working-directory not working as expected.

### ISSUE THREAD

**Issue by vveliev** [zgosalvez/github-actions-report-lcov#300]
When configuring `working-directory` to be `./app` i'm expecting that file reports will be sourced relative to the path. However this is not the case and at the moment as the workaround I need to set coverage file with workdir.

###  Usage case

when I have code in the ./app folder, with coverage inside ./app/coverage/lcov.info'

I'm expecting this  to work=
```yaml
    - name: Report Code Coverage
      uses: zgosalvez/github-actions-report-lcov@v4
      with:
        coverage-files: ${{ inputs.coverage-files }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
        working-directory: ${{ inputs.workdir }}
```

workaround:
```yaml
    - name: Report Code Coverage
      uses: zgosalvez/github-actions-report-lcov@v4
      with:
        coverage-files: " ${{ inputs.workdir }}/${{ inputs.coverage-files }}"
        github-token: ${{ secrets.GITHUB_TOKEN }}
        working-directory: ${{ inputs.workdir }}
```
