### ISSUE TITLE
Unable to resolve action

### ISSUE THREAD

**Issue by moseskarunia** [zgosalvez/github-actions-report-lcov#6]
# Yaml
```yaml
name: horeekaa

on:
  push:
    branches: [master]
    paths:
      - ".github/workflows/horeekaa.yaml"
      - "apps/horeekaa/**"
  pull_request:
    branches: [master, epic-**]
    paths:
      - ".github/workflows/horeekaa.yaml"
      - "apps/horeekaa/**"

jobs:
  build:
    defaults:
      run:
        working-directory: apps/horeekaa
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.4.0
      - name: Install dependencies
        run: flutter pub get
      - name: Format
        run: flutter format --set-exit-if-changed lib test
      - name: Analyze project source
        run: flutter analyze lib test
      - name: Test
        run: flutter test --coverage
      - name: Report code coverage
        uses: zgosalvez/github-actions-report-lcov@1.3.0
        with:
          working-directory: apps/horeekaa
          coverage-files: apps/horeekaa/coverage/lcov.info
          minimum-coverage: 95
          artifact-name: code-coverage-report
          github-token: ${{ secrets.GITHUB_TOKEN }}
```

# Log
> Current runner version: '2.276.1'
> Operating System
> Virtual Environment
> Prepare workflow directory
> Prepare all required actions
> Getting action download info
> Failed to resolve action download info. Error: Unable to resolve action `zgosalvez/github-actions-report-lcov@1.3.0`, unable to find version `1.3.0`
> Retrying in 14.083 seconds
> Failed to resolve action download info. Error: Unable to resolve action `zgosalvez/github-actions-report-lcov@1.3.0`, unable to find version `1.3.0`
> Retrying in 10.631 seconds
> Error: Unable to resolve action `zgosalvez/github-actions-report-lcov@1.3.0`, unable to find version `1.3.0`

Hi, I can't seem able to run using the latest released version from the github action marketplace. Maybe there's something wrong with the release process or how long should it be usually before available?

Thanks.
