### ISSUE TITLE
Failed to retrieve file names from artifact

### ISSUE THREAD

**Issue by Stanislaw000** [zgosalvez/github-actions-report-lcov#9]
Hello,

I have problem adding your action to my CI workflows:

I have 2 workflows 

First go CI, which builds app, run tests and upload test results and coverage as artifacts. This one is complete with success state and uploads artifacts:
<img width="976" alt="image" src="https://user-images.githubusercontent.com/44289106/128340588-1d2792c6-3fcb-400b-9676-df700452f0d6.png">

After workflow [CI] is completed my second workflow is triggered, which should process tests and coverage reports:

```
name: 'Test Report and Code Coverage'

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]
  
jobs:
  report:
    name: Workflow test
    runs-on: ubuntu-latest
    steps:
    - name: .NET Tests Results
      uses: dorny/test-reporter@v1
      with:
        artifact: test-results
        name: .NET Tests results           
        path: '**/**/*.trx'    
        reporter: dotnet-trx  
    - name: Code Coverage
      uses: zgosalvez/github-actions-report-lcov@v1
      with:
        artifact-name: code-coverage-report
        name: Code Coverage
        coverage-files: '**/TestResults/coverage.info'
        minimum-coverage: 0
        github-token: ${{ secrets.GITHUB_TOKEN }}
```

While tests reported is working as expected (so artifacts seems to be working), code coverage isn't.

It is failing with following error:
<img width="815" alt="image" src="https://user-images.githubusercontent.com/44289106/128340977-2da89def-5ac1-4825-8ee9-17af10903999.png">

I was playing witch changing .info file retrieving patterns, but doesn't help.

What is interesting is that when I had code coverage inside the same workflow as running tests it was working.

Any idea what's the problem here?

Links:
1. Tests and coverage processing action log: https://github.com/Stanislaw000/ONIX-Data/runs/3244608588?check_suite_focus=true
2. Build, test and artifacts upload action log: https://github.com/Stanislaw000/ONIX-Data/runs/3244213227?check_suite_focus=true
3. Coverage processing workflow: https://github.com/Stanislaw000/ONIX-Data/blob/NetStandard/.github/workflows/test-report.yml (default branch version, because this one is always working as being triggered by workflow complete)
4. CI workflow: https://github.com/Stanislaw000/ONIX-Data/blob/Test-Report-and-Code-Coverage-CI-improve/.github/workflows/ci.yml
